- platform: rest
  name: Kitchen Tablet Settings
  json_attributes:
    - timeToScreenOffV2
    - screenBrightness
    - motionSensitivity
    - motionDection
    - motionDetectionAcoustic
    - motionSensitivityAcoustic
    - screenOffInDarkness
    - darknessLevel
  resource: !secret tablet_settings
  value_template: '{{ value_json.motionSensitivity }}'
  scan_interval: 10