---
# Boolean Sensors are gathering information about states and conditions.
#
# This loads up my boolean sensor configurations
#
# https://www.home-assistant.io/integrations/sensor/
#
sensor: !include_dir_merge_list ../entities/boolean_sensors