alias: Mark person as home
trigger:
  - platform: state
    entity_id: input_select.mitra_status_dropdown
    to: 'Just Arrived'
    for:
      minutes: 10
  - platform: state
    entity_id: input_select.tom_status_dropdown
    to: 'Just Arrived'
    for:
      minutes: 10
  - platform: state
    entity_id: input_select.mitra_status_dropdown
    from: 'Just Left'
    to: 'Just Arrived'
  - platform: state
    entity_id: input_select.tom_status_dropdown
    from: 'Just Left'
    to: 'Just Arrived'
action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'input_boolean.is_mitra_home' %}
          input_select.mitra_status_dropdown
        {% else %}
          input_select.tom_status_dropdown
        {% endif %}
      option: Home