
- alias: Mark person as just arrived
  trigger:
    - platform: state
      entity_id: input_boolean.is_mitra_home
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.is_tom_home
      from: 'off'
      to: 'on'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_boolean.is_mitra_home' %}
            input_select.mitra_status_dropdown
          {% else %}
            input_select.tom_status_dropdown
          {% endif %}
        option: >
          {% if trigger.entity_id == 'input_boolean.is_mitra_home' %}
            {% if states.input_select.mitra_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% else %}
            {% if states.input_select.tom_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% endif %}

- alias: Mark person as home
  trigger:
    - platform: state
      entity_id: input_select.mitra_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.tom_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.mitra_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.tom_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_boolean.is_mitra_home' %}
            input_select.mitra_status_dropdown
          {% else %}
            input_select.tom_status_dropdown
          {% endif %}
        option: Home

- alias: Mark person as just left
  trigger:
    - platform: state
      entity_id: input_boolean.is_mitra_home
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: input_boolean.is_tom_home
      from: 'on'
      to: 'off'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_boolean.is_mitra_home' %}
            input_select.mitra_status_dropdown
          {% else %}
            input_select.tom_status_dropdown
          {% endif %}
        option: Just Left

- alias: Mark person as away
  trigger:
    - platform: state
      entity_id: input_select.mitra_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.tom_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.mitra_status_dropdown' %}
            input_select.mitra_status_dropdown
          {% else %}
            input_select.tom_status_dropdown
          {% endif %}
        option: Away

- alias: Mark person as extended away
  trigger:
    - platform: state
      entity_id: input_select.mitra_status_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.tom_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.mitra_status_dropdown' %}
            input_select.mitra_status_dropdown
          {% else %}
            input_select.tom_status_dropdown
          {% endif %}
        option: Extended Away
