esphome:
  name: master_bedroom_dimmer
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_user
  password: !secret wifi_password
  manual_ip: 
    static_ip: !secret dim_static_ip
    gateway: !secret dim_gateway
    subnet: !secret dim_subnet
    dns1: !secret dim_dns1
    dns2: !secret dim_dns2
    
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_pass

captive_portal:

# Make sure logging is not using the serial port
logger:
  baud_rate: 0
  level: DEBUG
  
#mqtt:
#  broker: !secret mqtt_broker
#  username: !secret mqtt_user
#  password: !secret mqtt_pass  

# Enable Home Assistant API
api:

ota:
  safe_mode: True

# My dimmer used the hardware serial port on the alternate pins
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Make the light
light:
  - platform: "tuya"
    name: "Master Bedroom Dimmer"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 10
    max_value: 1000
    default_transition_length: 30s