esphome:
  name: stair_dimmer
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_user
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stair Dimmer Fallback Hotspot"
    password: "xjoYIgbKIdJX"

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG
# Enable Home Assistant API
api:
  port: 6054

ota:
  safe_mode: True

# My dimmer used the hardware serial port on the alternate pins
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Make the light
light:
  - platform: "tuya"
    name: "Stairway Dimmer"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 10
    max_value: 1000
  