- platform: mqtt
  name: "Office Light"
  state_topic: "shellies/shelly1-B8FF1C/relay/0"
  command_topic: "shellies/shelly1-B8FF1C/relay/0/command"
  availability_topic: "shellies/shelly1-B8FF1C/online"
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"